# Generated by Django 5.0.4 on 2024-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='Message_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
